export const products = [
	{
		id: 1,
		name: "Wireless Bluetooth Headphones",
		category: "Electronics",
		price: 59.99,
		stock: 35,
		description:
			"High-quality wireless headphones with noise-cancellation and long battery life.",
		rating: 4.5,
		imageUrl: "https://example.com/images/headphones.jpg",
	},
	{
		id: 2,
		name: "Smartwatch",
		category: "Wearables",
		price: 149.99,
		stock: 12,
		description:
			"Stylish smartwatch with fitness tracking, heart-rate monitor, and customizable watch faces.",
		rating: 4.2,
		imageUrl: "https://example.com/images/smartwatch.jpg",
	},
	{
		id: 3,
		name: "Espresso Coffee Maker",
		category: "Home Appliances",
		price: 89.99,
		stock: 20,
		description: "Compact espresso machine for quick and rich coffee brewing at home.",
		rating: 4.7,
		imageUrl: "https://example.com/images/coffee-maker.jpg",
	},
	{
		id: 4,
		name: "Leather Office Chair",
		category: "Furniture",
		price: 199.99,
		stock: 7,
		description:
			"Ergonomic leather chair designed for comfort and productivity during long working hours.",
		rating: 4.8,
		imageUrl: "https://example.com/images/office-chair.jpg",
	},
	{
		id: 5,
		name: "Gaming Laptop",
		category: "Computers",
		price: 1099.99,
		stock: 5,
		description:
			"High-performance gaming laptop with NVIDIA GTX graphics, 16GB RAM, and 512GB SSD.",
		rating: 4.6,
		imageUrl: "https://example.com/images/gaming-laptop.jpg",
	},
	{
		id: 6,
		name: "4K Smart TV",
		category: "Electronics",
		price: 499.99,
		stock: 10,
		description: "55-inch 4K UHD smart TV with built-in streaming services and HDR support.",
		rating: 4.4,
		imageUrl: "https://example.com/images/smart-tv.jpg",
	},
	{
		id: 7,
		name: "Fitness Tracker",
		category: "Wearables",
		price: 69.99,
		stock: 25,
		description:
			"Waterproof fitness tracker with step counter, sleep monitor, and smartphone notifications.",
		rating: 4.1,
		imageUrl: "https://example.com/images/fitness-tracker.jpg",
	},
	{
		id: 8,
		name: "Electric Toothbrush",
		category: "Personal Care",
		price: 39.99,
		stock: 50,
		description:
			"Rechargeable electric toothbrush with multiple brushing modes and long-lasting battery.",
		rating: 4.3,
		imageUrl: "https://example.com/images/toothbrush.jpg",
	},
	{
		id: 9,
		name: "Instant Pot",
		category: "Kitchen Appliances",
		price: 89.99,
		stock: 18,
		description: "7-in-1 programmable pressure cooker, slow cooker, rice cooker, and more.",
		rating: 4.9,
		imageUrl: "https://example.com/images/instant-pot.jpg",
	},
	{
		id: 10,
		name: "Wireless Charging Pad",
		category: "Accessories",
		price: 24.99,
		stock: 40,
		description: "Fast wireless charging pad compatible with iPhone and Android devices.",
		rating: 4.0,
		imageUrl: "https://example.com/images/charging-pad.jpg",
	},
]
